[package]
name = "vardoku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
rand = "0.8.5"
sudoku = "0.8.0"
